### ISSUE TITLE
Некорректное сравнение с empty

### ISSUE THREAD

**Issue by asylum29** [MarkDvoryanchikov/CurrencyMini#4]
В valute.js в _uploadPlease()_ осуществляется некорректное сравнение данных сервера со строкой "empty". С сервера получена не строка, а массив, содержащий один элемент - строку "empty". Как результат - некорректная отработка скриптов в случае отсутствия валют для выбора / отображения в списке выбранных.

**На сервере:**
>    if (empty($mainarr)) $mainarr[] = "empty";
    if (empty($mainarr2)) $mainarr2[] = "empty";

**На клиенте:**
>if (data.data1 !== "empty"){
                ...
            }
            if (data.data2 !== "empty") {
                ...
            }

**Comment by MarkDvoryanchikov** [comment]
Подправлено.
